queue_rules:
  - name: default
    merge_conditions:
      - check-success=Evaluate flake.nix
      - check-success=check clippy [x86_64-linux]
      - check-success=check t00-simple [aarch64-linux]
      - check-success=check t00-simple [x86_64-linux]
      - check-success=check t01-signing [aarch64-linux]
      - check-success=check t01-signing [x86_64-linux]
      - check-success=check t02-varnish [aarch64-linux]
      - check-success=check t02-varnish [x86_64-linux]
      - check-success=check treefmt [aarch64-linux]
      - check-success=check treefmt [x86_64-linux]
      - check-success=devShell default [aarch64-darwin]
      - check-success=devShell default [aarch64-linux]
      - check-success=devShell default [x86_64-linux]
      - check-success=package default [aarch64-darwin]
      - check-success=package default [aarch64-linux]
      - check-success=package default [x86_64-linux]
      - check-success=package harmonia [aarch64-darwin]
      - check-success=package harmonia [aarch64-linux]
      - check-success=package harmonia [x86_64-linux]
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      queue: {}
